// 영어 단어 데이터 001-100 (새 단어책)
const words = [
    {eng: "community",     kor: "지역 사회",                blank: "c o m m u n _ t _"},
    {eng: "teamwork",      kor: "팀워크",                   blank: "t e a m w _ r _"},
    {eng: "optimistic",    kor: "낙관적인",                 blank: "o p t _ m i s t _ c"},
    {eng: "creative",      kor: "창의적인",                 blank: "c r _ a t _ v e"},
    {eng: "enthusiastic",  kor: "열정적인",                 blank: "e n t h u s _ a s t _ c"},
    {eng: "supportive",    kor: "지지하는",                 blank: "s u p p _ r t _ v e"},
    {eng: "dedicate",      kor: "헌신하다",                 blank: "d e d _ c _ t e"},
    {eng: "inspiring",     kor: "영감을 주는",               blank: "i n s p _ r _ n g"},
    {eng: "choir",         kor: "합창단",                   blank: "c h _ i r"},
    {eng: "fundraising",   kor: "모금 활동",                blank: "f u n d r _ i s _ n g"},
    {eng: "authentic",     kor: "진정한, 진짜의",            blank: "a u t h _ n t _ c"},
    {eng: "respectful",    kor: "존경하는",                 blank: "r _ s p e c t f _ l"},
    {eng: "positive",      kor: "긍정적인",                 blank: "p _ s i t _ v e"},
    {eng: "local",         kor: "지역의",                   blank: "l _ c a l"},
    {eng: "proud",         kor: "자랑스러운",               blank: "p r _ u d"},
    {eng: "success",       kor: "성공",                    blank: "s u c c _ s _"},
    {eng: "charming",      kor: "매력적인",                 blank: "c h a r m _ n _"},
    {eng: "take part",     kor: "참가하다",                 blank: "t a k e  p _ r _"},
    {eng: "trustworthy",   kor: "신뢰할 수 있는",            blank: "t r u s t w _ r t h _"},
    {eng: "appearance",    kor: "외모",                    blank: "a p p _ a r a n c _"},
    {eng: "chubby",        kor: "통통한",                   blank: "c h u b b _"},
    {eng: "freckled",      kor: "주근깨가 있는",             blank: "f r _ c k l _ d"},
    {eng: "thoughtful",    kor: "사려 깊은",                blank: "t h _ u g h t f _ l"},
    {eng: "outgoing",      kor: "외향적인",                 blank: "o u t g o _ n _"},
    {eng: "encouraging",   kor: "격려하는",                 blank: "e n c o u r _ g _ n g"},
    {eng: "sociable",      kor: "사교적인",                 blank: "s o c _ a b _ e"},
    {eng: "generous",      kor: "너그러운",                 blank: "g e n _ r _ u s"},
    {eng: "personality",   kor: "성격, 인격",               blank: "p e r s _ n a l _ t y"},
    {eng: "gorgeous",      kor: "화려한, 아름다운",           blank: "g _ r g _ o u s"},
    {eng: "typical",       kor: "전형적인",                 blank: "t y p _ c _ l"},
    {eng: "pretend",       kor: "~인 척하다",               blank: "p r _ t _ n d"},
    {eng: "admirable",     kor: "존경할 만한",               blank: "a d m _ r a b _ e"},
    {eng: "kindness",      kor: "친절, 친절함",              blank: "k _ n d n _ s s"},
    {eng: "individual",    kor: "개인, 개인의",              blank: "i n d _ v i d _ a l"},
    {eng: "caring",        kor: "배려하는",                 blank: "c _ r i n g"},
    {eng: "intelligent",   kor: "지적인",                   blank: "i n t _ l l i g _ n t"},
    {eng: "genuine",       kor: "진실한",                   blank: "g e n _ i n _"},
    {eng: "talented",      kor: "재능 있는",                blank: "t a l _ n t _ d"},
    {eng: "humble",        kor: "겸손한",                   blank: "h _ m b l e"},
    {eng: "reliable",      kor: "믿을 수 있는",              blank: "r e l _ a b _ e"},
    {eng: "wise",          kor: "지혜로운",                 blank: "w _ s e"},
    {eng: "resilient",     kor: "회복력이 있는",             blank: "r e s _ l i _ n t"},
    {eng: "empathetic",    kor: "공감하는",                 blank: "e m p a t h _ t _ c"},
    {eng: "independent",   kor: "독립적인",                 blank: "i n d _ p e n d _ n t"},
    {eng: "persistent",    kor: "끈기 있는",                blank: "p _ r s i s t _ n t"},
    {eng: "motivating",    kor: "동기를 부여하는",           blank: "m o t _ v a t _ n g"},
    {eng: "selfless",      kor: "사심 없는, 이타적인",        blank: "s e l f l _ s _"},
    {eng: "gracious",      kor: "우아한, 품위 있는",          blank: "g r _ c i _ u s"},
    {eng: "understanding", kor: "이해심 있는",               blank: "u n d _ r s t a n d _ n g"},
    {eng: "honest",        kor: "정직한",                   blank: "h _ n e s t"},
    {eng: "traditional",   kor: "전통적인",                 blank: "t r a d _ t i _ n a l"},
    {eng: "archery",       kor: "양궁",                    blank: "a r c h _ r _"},
    {eng: "national",      kor: "국가의, 국민의",             blank: "n a t _ o n _ l"},
    {eng: "prayer",        kor: "기도",                    blank: "p r _ y e r"},
    {eng: "breeze",        kor: "산들바람",                 blank: "b r _ e z e"},
    {eng: "Himalayas",     kor: "히말라야",                 blank: "H i m _ l a y _ s"},
    {eng: "nod",           kor: "고개를 끄덕이다",           blank: "n _ d"},
    {eng: "greet",         kor: "인사하다",                 blank: "g r _ e t"},
    {eng: "peaceful",      kor: "평화로운",                 blank: "p e a c _ f _ l"},
    {eng: "remember",      kor: "기억하다",                 blank: "r e m _ m b _ r"},
    {eng: "flap",          kor: "펄럭이다",                 blank: "f l _ p"},
    {eng: "history",       kor: "역사",                    blank: "h i s t _ r _"},
    {eng: "backdrop",      kor: "배경",                    blank: "b _ c k d r _ p"},
    {eng: "decide",        kor: "결정하다",                 blank: "d _ c i d e"},
    {eng: "overwhelmed",   kor: "압도된",                   blank: "o v _ r w h e l m _ d"},
    {eng: "attire",        kor: "복장, 의상",               blank: "a t t _ r e"},
    {eng: "indifferent",   kor: "무관심한",                 blank: "i n d _ f f e r _ n t"},
    {eng: "offer",         kor: "제공하다",                 blank: "o f f _ r"},
    {eng: "observe",       kor: "관찰하다",                 blank: "o b s _ r v _"},
    {eng: "be eager to",   kor: "~을 열망하다",              blank: "b e  _ a g e r  t _"},
    {eng: "cathedral",     kor: "대성당",                   blank: "c a t h _ d r _ l"},
    {eng: "failure",       kor: "실패",                    blank: "f a _ l u r _"},
    {eng: "proverb",       kor: "속담",                    blank: "p r _ v _ r b"},
    {eng: "be fond of",    kor: "~을 좋아하다",              blank: "b e  f _ n d  o _"},
    {eng: "indefinite",    kor: "부정의, 막연한",             blank: "i n d _ f i n _ t e"},
    {eng: "pronoun",       kor: "대명사",                   blank: "p r _ n _ u n"},
    {eng: "exotic",        kor: "이국적인",                 blank: "e x _ t i c"},
    {eng: "architecture",  kor: "건축",                    blank: "a r c h _ t e c t _ r e"},
    {eng: "cuisine",       kor: "요리",                    blank: "c u _ s i n _"},
    {eng: "wildlife",      kor: "야생 동물",                blank: "w _ l d l _ f e"},
    {eng: "climate",       kor: "기후",                    blank: "c l _ m a t _"},
    {eng: "diversity",     kor: "다양성",                   blank: "d i v _ r s _ t y"},
    {eng: "religious",     kor: "종교적인",                 blank: "r _ l i g _ o u s"},
    {eng: "hospitality",   kor: "환대",                    blank: "h o s p _ t a l _ t y"},
    {eng: "ancient",       kor: "고대의",                   blank: "a n c _ e n _"},
    {eng: "represent",     kor: "대표하다",                 blank: "r _ p r e s _ n t"},
    {eng: "urban",         kor: "도시의",                   blank: "u r b _ n"},
    {eng: "custom",        kor: "관습",                    blank: "c u s t _ m"},
    {eng: "rural",         kor: "시골의",                   blank: "r _ r a l"},
    {eng: "industry",      kor: "산업",                    blank: "i n d _ s t r _"},
    {eng: "souvenir",      kor: "기념품",                   blank: "s _ u v _ n i r"},
    {eng: "completely",    kor: "완전히",                   blank: "c o m p l _ t e l _"},
    {eng: "incredibly",    kor: "믿을 수 없을 만큼",          blank: "i n c r _ d i b l _"},
    {eng: "purpose",       kor: "목적, 용도",               blank: "p u r p _ s _"},
    {eng: "method",        kor: "방법",                    blank: "m _ t h o d"},
    {eng: "pleasure",      kor: "즐거움",                   blank: "p l _ a s _ r e"},
    {eng: "scenic",        kor: "경치 좋은",                blank: "s c _ n i c"},
    {eng: "landmark",      kor: "주요 장소, 랜드마크",        blank: "l _ n d m _ r k"},
    {eng: "comfort",       kor: "안락함, 위로",              blank: "c o m f _ r _"},
    {eng: "rapidly",       kor: "빠르게",                   blank: "r _ p i d l _"},

    // 101-120
    {eng: "rural community",  kor: "시골 지역, 농촌 지역",      blank: "r _ r a l  c o m m _ n i t y"},
    {eng: "adventure",        kor: "모험",                     blank: "a d v _ n t _ r e"},
    {eng: "conservation",     kor: "보존, 자연보호",             blank: "c o n s _ r v a t _ o n"},
    {eng: "activity",         kor: "활동",                     blank: "a c t _ v _ t y"},
    {eng: "heritage",         kor: "유산, 전통",                blank: "h _ r i t _ g e"},
    {eng: "tourism",          kor: "관광",                     blank: "t _ u r _ s m"},
    {eng: "culture",          kor: "문화",                     blank: "c _ l t _ r e"},
    {eng: "protect",          kor: "보호하다",                  blank: "p r _ t _ c t"},
    {eng: "cliff",            kor: "절벽",                     blank: "c l _ f f"},
    {eng: "waterfall",        kor: "폭포",                     blank: "w _ t e r f _ l l"},
    {eng: "visitor",          kor: "방문자",                   blank: "v _ s i t _ r"},
    {eng: "diligently",       kor: "부지런히, 열심히",           blank: "d _ l i g e n t _ y"},
    {eng: "spend",            kor: "사용하다, 보내다",           blank: "s p _ n d"},
    {eng: "explore",          kor: "탐험하다",                  blank: "e x p l _ r _"},
    {eng: "important",        kor: "중요한",                   blank: "i m p o r t _ n _"},
    {eng: "recognition",      kor: "인식, 인정",                blank: "r e c _ g n i t _ o n"},
    {eng: "immense",          kor: "거대한",                   blank: "i m m _ n s _"},
    {eng: "employment",       kor: "고용",                     blank: "e m p l _ y m _ n t"},
    {eng: "profound",         kor: "깊은, 심오한",              blank: "p r _ f _ u n d"},
    {eng: "preserve",         kor: "보존하다",                  blank: "p r e s _ r v _"},
    // 121-140
    {eng: "structure",        kor: "구조",                     blank: "s t r _ c t _ r e"},
    {eng: "unusual",          kor: "특이한",                   blank: "u n _ s u _ l"},
    {eng: "uncertainty",      kor: "불확실성",                  blank: "u n c _ r t a _ n t y"},
    {eng: "affirmative",      kor: "긍정적인, 긍정응답",         blank: "a f f _ r m a t _ v e"},
    {eng: "interrogative",    kor: "의문형의",                  blank: "i n t _ r r o g a t _ v e"},
    {eng: "relative",         kor: "친척",                     blank: "r _ l a t _ v e"},
    {eng: "coordination",     kor: "조정, 협력, 조직화",         blank: "c o _ r d i n a t _ o n"},
    {eng: "emotion",          kor: "감정",                     blank: "e m _ t _ o n"},
    {eng: "objective",        kor: "목표, 객관적인",             blank: "o b j _ c t _ v e"},
    {eng: "unexpected",       kor: "예상치 못한",               blank: "u n _ x p e c t _ d"},
    {eng: "unique",           kor: "유일무이한, 독특한",          blank: "u n _ q u e"},
    {eng: "meaningful",       kor: "의미 있는",                 blank: "m _ a n i n g f u l"},
    {eng: "treasure",         kor: "귀하게 여기다, 보물",         blank: "t r _ a s _ r e"},
    {eng: "heartwarming",     kor: "마음을 따뜻하게 하는",        blank: "h _ a r t w a r m _ n g"},
    {eng: "journey",          kor: "여행, 여정",                blank: "j _ u r n _ y"},
    {eng: "inspiration",      kor: "영감",                     blank: "i n s p _ r a t _ o n"},
    {eng: "interest",         kor: "관심, 흥미",                blank: "i n t _ r _ s t"},
    {eng: "accomplishment",   kor: "성취",                     blank: "a c c _ m p l i s h m _ n t"},
    {eng: "factor",           kor: "요소",                     blank: "f _ c t o r"},
    {eng: "concern",          kor: "관심사, 걱정",              blank: "c _ n c _ r n"},
    // 141-150
    {eng: "precious",         kor: "소중한",                   blank: "p r _ c i _ u s"},
    {eng: "reflection",       kor: "모습, 반사, 반영",           blank: "r _ f l e c t _ o n"},
    {eng: "joyful",           kor: "기쁜",                     blank: "j _ y f u l"},
    {eng: "relationship",     kor: "관계",                     blank: "r e l _ t i o n s h _ p"},
    {eng: "attention",        kor: "주의, 주목",                blank: "a t t _ n t _ o n"},
    {eng: "experience",       kor: "경험하다, 경험",             blank: "e x p _ r i e n c _"},
    {eng: "moment",           kor: "순간",                     blank: "m _ m e n t"},
    {eng: "strategy",         kor: "전략",                     blank: "s t r _ t _ g y"},
    {eng: "specific",         kor: "구체적인, 특정의",           blank: "s p _ c _ f i c"},
    {eng: "politely",         kor: "공손하게, 예의 바르게",       blank: "p _ l i t _ l y"},
];